### ISSUE TITLE
crash in bucketeer

### ISSUE THREAD

**Issue by fginter** [TurkuNLP/Turku-neural-parser-pipeline#2]
can be replicated with ```((while $(true) ; do cat long.txt ; done) | python3 full_pipeline_stream.py --conf-yaml models_fi_tdt/pipelines.yaml) > log2.conllu 2> log.err``` on gpu1

```
Traceback (most recent call last):
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/dataset.py", line 61, in __init__
    splits = bucketer.compute_splits(len(sent) for sent,metadata in self.iterfiles())
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/misc/bucketer.py", line 90, in compute_splits
    self.recenter()
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/misc/bucketer.py", line 118, in recenter
    lidx = self.lidxs[idx]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ginter/Turku-neural-parser-pipeline/parser_mod.py", line 23, in launch
    conllu=parser.parse_text(txt)
  File "/home/ginter/Turku-neural-parser-pipeline/parser_lib.py", line 101, in parse_text
    return self.parse_generator.__next__()
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/network.py", line 411, in parse_generator
    parseset = Parseset.from_configurable(self, self.vocabs, parse_files=self.current_input, nlp_model=self.nlp_model)
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/configurable.py", line 113, in from_configurable
    return cls(*args, **kwargs)
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/dataset.py", line 63, in __init__
    splits[i] += 1
  File "/home/ginter/Turku-neural-parser-pipeline/Parser-v2/parser/misc/bucketer.py", line 243, in __exit__
    raise exception_type(exception_value)
IndexError: list index out of range
Feeding a batch
Traceback (most recent call last):
  File "/home/ginter/Turku-neural-parser-pipeline/parser_mod.py", line 23, in launch
    conllu=parser.parse_text(txt)
  File "/home/ginter/Turku-neural-parser-pipeline/parser_lib.py", line 101, in parse_text
    return self.parse_generator.__next__()
```

**Comment by jmnybl** [comment]
This should now be fixed with 2f1a7c784cac80f519081fb4534e8882d1b9c2bd.
